---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-application 
  name: web-application
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web-application
  template:
    metadata:
      labels:
        app: web-application
    spec:
      containers:
      - image: adhishkapoor1607/web-api  
        name: web-application
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "0.3"
            memory: "512Mi"
          requests:
            cpu: "0.3"
            memory: "256Mi"
        env:
          - name: FLASK_APP
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: FLASK_APP
          - name: MYSQL_ROOT_USER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MYSQL_ROOT_USER
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
          - name: MYSQL_ROOT_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MYSQL_ROOT_HOST
          - name: MYSQL_ROOT_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MYSQL_ROOT_PORT
          - name: MYSQL_ROOT_DB
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MYSQL_ROOT_DB

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  ports:
  - port: 8282
    protocol: TCP
    targetPort: 8282
  selector:
    app: web-application
  type: LoadBalancer
